### ISSUE TITLE
Выбор сервера

### ISSUE THREAD

**Issue by instmaxinc** [get-web/unitpay-ajax-form#1]
Вопрос такой как организовать данный скрипт с выбором (сервера и т.п.)

**Comment by get-web** [comment]
Готового решения пока нет. Конкретно эта версия делалась как стандартная форма. 
Выбор сервера, это уже модификация под конкретную тематику и если это действительно  будет востребовано, я выделю время и напишу. Возможно создам отдельную ветку для lineage 2 серверов

Вообще как быстрое решение без изменения цены, можно вместо проверки публичного ключа:
```
if ($publicKey != $_POST['publicKey']) {
    array_push($errors, 'Подмена публичного ключа');
}
```
Сделать присвоение:
`$publicKey = $_POST['publicKey']`

В html убираем:
`<input type="hidden" name="publicKey" value="000000-000000" data-unitpay="publicKey">`

Добавляем в нужном месте select со списком серверов и публичными ключами в value:
```
<select name="publicKey">
    <option value="000000-000000">Сервер 1</option>
    <option value="000000-000000">Сервер 2</option>
</select>
```

UPDATE: Но тут еще важный момент, если секретный ключ разный для каждого магазина, тогда такой метод не сработает.

**Comment by get-web** [comment]
Реализовано в обновлении [1.0.1](https://github.com/get-web/unitpay-ajax-form/releases/tag/1.0.1)
